CREATE DATABASE my_projects;
\c my_projects

CREATE TABLE projects(
id serial PRIMARY KEY NOT NULL,
name VARCHAR NOT NULL,
type VARCHAR NOT NULL,
status VARCHAR NOT NULL,
language_used VARCHAR NOT NULL,
url1 VARCHAR NOT NULL,
url2 VARCHAR NOT NULL,
url3 VARCHAR NOT NULL,
created_at VARCHAR NOT NULL,
link VARCHAR NOT NULL
);